name: Events Demo 1
on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:
  #only pushes to the main branch will trigger this workflow
  push:
    #filters branches
    branches:
      #Pattern matches for branch selection https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - main
      - dev
      - feat/** # feat/new feat/new/button ...
    #filters paths, triggers workflow if changes are detected in a specific path
    paths-ignore:
      - './github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
